# Generated by Django 3.0.7 on 2020-06-19 17:30

from django.db import migrations, models
import fileupload.models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='', validators=[fileupload.models.validate_file_extension]),
        ),
    ]
