# Generated by Django 3.0.7 on 2020-06-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('fileupload', '0003_file_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='groups',
            field=models.ManyToManyField(related_name='img_groups', to='auth.Group'),
        ),
    ]
