# Generated by Django 3.0.7 on 2020-06-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('fileupload', '0004_auto_20200626_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
